In [1]:
import cornac
from cornac.data import Reader
from cornac.datasets import movielens
from cornac.data import Dataset, FeatureModality
from cornac.eval_methods import RatioSplit, StratifiedSplit
from cornac.metrics import RMSE
from cornac.models import MF, ItemKNN, UserKNN, NMF, BPR
import pandas as pd
import numpy as np

import math
import seaborn as sns
import matplotlib.pyplot as plt


/Users/tahsinalamgirkheya/anaconda3/envs/cornac/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
reader = Reader()
rating_data = pd.read_csv(
    "./cornac/data_c/indexed_interactions.csv",
    sep="\t",
    header=None,
    names=["userID", "itemID", "Rating", "Timestamp"],
)
print(rating_data['itemID'].nunique())
# rating_data = rating_data.drop(columns=rating_data.columns[-1])
rating_data = rating_data.to_numpy()
rating_data
# user id itemid rating and timestamp

3416


array([[        0,         0,         5, 978300760],
       [        0,         1,         3, 978302109],
       [        0,         2,         3, 978301968],
       ...,
       [     6039,       365,         5, 956704746],
       [     6039,       152,         4, 956715648],
       [     6039,        26,         4, 956715569]])

In [3]:
# dataset = Dataset.from_uirt(rating_data, reader=reader)
dataset=rating_data


In [4]:
rating_data.shape

(999611, 4)

In [5]:
# movie_data = reader.read(fpath="./data/indexed_movies.csv", sep=",", fmt="UIRT")
# movie_data
movies = pd.read_csv("./cornac/data_c/indexed_movies.csv")

movies = movies.drop(columns=movies.columns[0])
movies[:4]

unique_genres = set("|".join(movies["genres"]).split("|"))
unique_genres = list(unique_genres)

for genre in unique_genres:
    movies[genre] = 0
for index, row in movies.iterrows():
    genres = row["genres"].split("|")
    for genre in genres:
        movies.at[index, genre] = 1

# item_categories = movies[unique_genres]
genre = movies[unique_genres]
item_features_numpy = genre.to_numpy()
# print(item_features_numpy.shape)

# item_categories = item_categor
item_features = {
    str(item_id): {"genre_" + str(idx): value for idx, value in enumerate(row)}
    for item_id, row in enumerate(item_features_numpy)
}
ids = list(range(0, 3416))
item_feature_modality = FeatureModality(
    features=item_features_numpy, ids=ids, normalized=True
)
item_feature_modality.__getstate__()
users = pd.read_csv("./cornac/data_c/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)

user_features_numpy = users.to_numpy()
print(user_features_numpy.shape)
user_feature_modality = FeatureModality(
    features=user_features_numpy, name="user", normalized=True, ids=list(range(0, 6040))
)

# print("Example Item Features:")
# for item_id, features in list(item_features.items())[:5]:
#     print(f"Item ID: {item_id}, Features: {features}")

(6040, 2)


In [6]:
item_features_numpy[4]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [7]:
# dataset.add_modalities(user_feature=user_feature_modality, item_features=item_feature_modality )
user_features_numpy

array([[   0,    1],
       [   1,    0],
       [   2,    0],
       ...,
       [6037,    1],
       [6038,    1],
       [6039,    0]])

In [8]:
ratio_split = StratifiedSplit(
    data=dataset, test_size=0.2, rating_threshold=0.0, seed=123, verbose=True, chrono=True,user_features = user_features_numpy[:,1]
)

model = MF(
    k=10, max_iter=50, learning_rate=0.001, lambda_reg=0.02, seed=123, name="lmd0.02", backend="pytorch", item_features=item_features_numpy
)

cornac.Experiment(
    ratio_split, models=[model], metrics=[cornac.metrics.RMSE(),cornac.metrics.AUC()]
).run()

rating_threshold = 0.0
exclude_unknowns = True
---
Training data:
Number of users = 6040
Number of items = 3415
Number of ratings = 797275
Max rating = 5.0
Min rating = 1.0
Global mean = 3.6
---
Test data:
Number of users = 6040
Number of items = 3415
Number of ratings = 202331
Number of unknown users = 0
Number of unknown items = 0
---
Total users = 6040
Total items = 3415

[lmd0.02] Training started!
-------------------
OrderedDict([(6039, 0), (6038, 1), (6037, 2), (6036, 3), (6035, 4), (6034, 5), (6033, 6), (6032, 7), (6031, 8), (6030, 9), (6029, 10), (6028, 11), (6027, 12), (6026, 13), (6025, 14), (6024, 15), (6023, 16), (6022, 17), (6021, 18), (6020, 19), (6019, 20), (6018, 21), (6017, 22), (6016, 23), (6015, 24), (6014, 25), (6013, 26), (6012, 27), (6011, 28), (6010, 29), (6009, 30), (6008, 31), (6006, 32), (6007, 33), (6005, 34), (6004, 35), (6003, 36), (6002, 37), (6001, 38), (6000, 39), (5999, 40), (5998, 41), (5997, 42), (5996, 43), (5995, 44), (5994, 45), (5993, 46), (5992, 

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.21]

./././././././.
tensor([2., 4., 4., 4., 5., 4., 4., 4., 1., 4., 1., 3., 5., 4., 5., 3., 3., 3.,
        3., 5., 5., 2., 2., 4., 4., 4., 3., 4., 4., 5., 4., 1., 3., 3., 5., 5.,
        3., 3., 3., 2., 4., 3., 4., 4., 4., 2., 3., 4., 4., 3., 3., 4., 1., 4.,
        5., 4., 4., 4., 5., 5., 4., 3., 3., 3., 3., 4., 4., 3., 5., 5., 3., 4.,
        2., 4., 4., 1., 2., 5., 4., 4., 4., 5., 5., 3., 4., 3., 4., 3., 4., 4.,
        5., 4., 4., 4., 1., 2., 3., 4., 5., 3., 4., 2., 4., 4., 2., 5., 4., 5.,
        1., 4., 5., 3., 5., 4., 3., 4., 2., 2., 5., 1., 5., 1., 5., 3., 4., 4.,
        4., 3., 4., 5., 4., 5., 5., 3., 4., 4., 2., 4., 5., 3., 1., 4., 5., 2.,
        2., 3., 4., 1., 5., 4., 3., 4., 5., 4., 5., 3., 4., 3., 5., 5., 4., 5.,
        2., 2., 3., 3., 4., 4., 2., 4., 4., 1., 5., 4., 4., 5., 4., 4., 5., 4.,
        5., 3., 4., 3., 4., 2., 5., 4., 1., 5., 3., 4., 4., 5., 3., 4., 3., 1.,
        4., 3., 5., 5., 4., 4., 5., 4., 3., 3., 4., 1., 4., 4., 4., 3., 4., 3.,
        4., 4., 2., 5., 

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.22]

tensor([4., 2., 5., 3., 2., 3., 2., 4., 4., 5., 4., 4., 5., 4., 5., 5., 2., 4.,
        3., 4., 1., 5., 1., 4., 5., 4., 3., 2., 4., 5., 4., 4., 5., 4., 4., 1.,
        4., 4., 2., 4., 2., 3., 5., 1., 4., 2., 3., 5., 5., 5., 4., 1., 4., 5.,
        5., 4., 2., 5., 2., 5., 5., 5., 5., 2., 5., 1., 3., 2., 5., 2., 4., 3.,
        4., 5., 5., 3., 4., 5., 2., 3., 4., 4., 5., 1., 5., 4., 2., 5., 1., 3.,
        3., 3., 5., 1., 4., 3., 2., 4., 4., 5., 3., 3., 5., 1., 4., 3., 5., 3.,
        3., 2., 5., 3., 4., 3., 3., 4., 3., 4., 4., 3., 3., 5., 5., 5., 5., 4.,
        5., 3., 5., 4., 3., 4., 4., 5., 4., 5., 5., 3., 5., 2., 3., 4., 4., 4.,
        4., 4., 5., 5., 5., 5., 1., 3., 5., 2., 4., 5., 1., 2., 2., 5., 1., 5.,
        3., 5., 4., 2., 4., 4., 1., 5., 4., 5., 4., 3., 4., 4., 3., 5., 3., 5.,
        3., 3., 4., 4., 3., 3., 5., 5., 4., 3., 4., 2., 3., 3., 3., 3., 1., 3.,
        4., 5., 1., 4., 3., 4., 5., 1., 5., 2., 4., 5., 3., 4., 2., 5., 3., 4.,
        4., 4., 5., 4., 1., 2., 3., 3., 

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.22]

tensor([4., 3., 2., 4., 5., 4., 4., 4., 3., 4., 5., 5., 5., 4., 5., 3., 2., 5.,
        4., 4., 3., 3., 5., 4., 3., 4., 5., 3., 2., 4., 4., 4., 4., 5., 3., 3.,
        4., 3., 4., 3., 2., 2., 4., 5., 4., 5., 4., 4., 5., 2., 2., 1., 3., 4.,
        3., 3., 3., 3., 1., 4., 5., 3., 3., 4., 4., 5., 5., 4., 2., 3., 1., 3.,
        4., 4., 4., 4., 2., 3., 1., 4., 3., 5., 2., 3., 5., 4., 5., 4., 5., 1.,
        5., 5., 4., 3., 4., 4., 3., 5., 2., 5., 5., 3., 5., 4., 4., 3., 2., 3.,
        3., 3., 2., 3., 3., 3., 4., 5., 4., 4., 3., 3., 4., 3., 4., 1., 1., 3.,
        2., 1., 2., 3., 5., 5., 4., 3., 5., 4., 1., 1., 4., 3., 2., 3., 4., 4.,
        2., 5., 4., 4., 5., 4., 3., 5., 3., 4., 5., 5., 4., 4., 5., 3., 3., 4.,
        5., 2., 3., 5., 4., 5., 3., 3., 4., 3., 3., 5., 5., 2., 3., 4., 5., 4.,
        3., 4., 2., 3., 3., 4., 4., 3., 5., 2., 3., 1., 2., 2., 4., 2., 4., 3.,
        3., 5., 3., 4., 4., 2., 4., 4., 3., 2., 4., 5., 4., 1., 3., 4., 4., 3.,
        5., 4., 1., 5., 5., 4., 3., 2., 

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.22]

./././././././.
tensor([4., 5., 4., 3., 2., 4., 5., 4., 2., 1., 4., 4., 3., 5., 3., 4., 5., 3.,
        5., 1., 3., 4., 4., 5., 3., 2., 4., 4., 4., 4., 5., 3., 3., 3., 3., 5.,
        3., 5., 2., 5., 4., 5., 3., 5., 4., 4., 4., 5., 1., 4., 1., 5., 4., 4.,
        2., 3., 5., 2., 5., 4., 3., 3., 2., 4., 4., 1., 3., 4., 4., 5., 5., 5.,
        3., 1., 2., 5., 3., 4., 2., 2., 5., 2., 4., 4., 4., 2., 3., 1., 5., 4.,
        4., 4., 4., 3., 3., 5., 3., 3., 5., 5., 3., 4., 5., 5., 3., 3., 4., 3.,
        5., 3., 1., 4., 4., 3., 5., 5., 2., 5., 3., 3., 2., 4., 4., 4., 5., 2.,
        3., 3., 3., 2., 4., 5., 2., 4., 2., 1., 2., 1., 3., 2., 2., 3., 1., 4.,
        3., 5., 3., 5., 2., 4., 5., 5., 4., 3., 5., 2., 3., 4., 5., 4., 5., 3.,
        4., 3., 4., 3., 3., 3., 5., 4., 3., 3., 3., 4., 4., 5., 3., 4., 1., 5.,
        5., 3., 3., 4., 4., 3., 3., 4., 3., 3., 3., 2., 5., 3., 2., 5., 4., 4.,
        2., 4., 2., 3., 4., 4., 3., 5., 4., 5., 3., 4., 5., 3., 5., 2., 4., 4.,
        5., 3., 1., 5., 

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.2] 

tensor([5., 3., 4., 2., 1., 1., 3., 4., 4., 5., 5., 2., 1., 5., 4., 4., 4., 2.,
        5., 4., 4., 5., 5., 4., 4., 5., 4., 4., 3., 4., 5., 5., 4., 3., 5., 3.,
        1., 4., 5., 4., 4., 3., 2., 4., 1., 4., 3., 3., 5., 3., 3., 1., 3., 3.,
        5., 4., 4., 3., 4., 2., 3., 4., 3., 4., 5., 4., 3., 3., 2., 5., 4., 5.,
        3., 2., 4., 5., 4., 2., 4., 4., 1., 2., 5., 4., 3., 5., 3., 3., 4., 5.,
        4., 5., 2., 4., 4., 4., 5., 3., 4., 5., 3., 4., 4., 3., 5., 4., 3., 2.,
        3., 5., 4., 4., 4., 3., 4., 3., 3., 3., 3., 4., 4., 4., 5., 2., 1., 5.,
        2., 5., 4., 2., 5., 3., 4., 3., 2., 4., 4., 4., 5., 4., 4., 3., 3., 5.,
        5., 4., 5., 4., 5., 1., 5., 4., 4., 3., 3., 4., 5., 1., 4., 5., 4., 3.,
        4., 2., 2., 5., 5., 5., 4., 4., 3., 3., 3., 2., 5., 5., 4., 4., 3., 3.,
        5., 4., 3., 3., 5., 5., 4., 5., 5., 3., 3., 4., 4., 5., 5., 2., 5., 5.,
        4., 3., 3., 5., 3., 4., 5., 5., 4., 4., 4., 5., 4., 1., 5., 4., 4., 2.,
        3., 5., 2., 2., 4., 5., 4., 5., 

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.2]

tensor([ 930,  141, 1658,  749,  886, 1704, 1827,  950,  443,  313,  826, 1606,
        2601, 1453, 1942, 3308,  823,  408,  206, 1780,  592, 1019,  300, 1113,
         150, 2594, 1048, 1071,  324, 1088, 1412,  736,   98, 1049, 1093,  498,
        1795,  423, 1730, 1936,  956, 2091,  235,  618, 1264,  478,  934,  875,
        1307,  279, 1064, 1305,  625,  117,  194,  937, 1374, 1420,  867, 2508,
          16,  648, 2618, 1691, 1519,  466, 1062,  706,  759,  222,    3, 1307,
         642,  203,  244, 1401, 1356,  862,  886,  685,  916, 2579, 1753,  595,
        1914, 1842,  950, 1707,  450, 2716,  146, 1711, 1811,  154, 1847, 2633,
           3, 1321,  824,  802, 1015,   93, 1597,  934,    0,  654, 1065, 1838,
         540,  891,  920,  459,  955,    1,   27,  179,  138, 1001,   83,  653,
        1036, 2709,  338,  750, 1517,  419,  915,  197,  417,  449,  915,  484,
        1141,  190, 1362,  428, 1290,  174,  412,  401,  219, 1356,   53,  214,
         125, 1109, 1082,  533, 2063,  2

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.2]

tensor([  14,  637,  244, 1539, 2183,  248, 1119, 2059,    2,  664, 1244,  205,
        1449,  967,  910,  278,  719, 1799,   25,  355,  448,  906,  133,  461,
         723,  210,  402,  251, 2130,  928, 1725, 1794, 1709, 1795,  367, 1978,
         740, 1364, 1928,  372,   97, 2986, 2238,  999,  348,  117,   27, 1364,
        1765,  961, 1387,  648,  466,  122, 1447,   84,  139, 1039, 2110, 1255,
        1122,  678,  692,  119,  114,  585, 2449, 1911,  962,   55,  662, 1794,
         459,  431, 1611,  629, 1774,  513, 1849, 2220, 1130, 1705,  115,   14,
          61,  903, 1394, 1378, 1069,  302,  793,  816, 2147,  119,   76,  972,
          25, 1372,  119,   21, 1477,  768, 1036,  495, 2841,  585, 2355, 1435,
         440,   16, 1353,  120,  170, 1189, 1079, 1625, 2607,  879,  130,  446,
         443,  194,  304, 1089,   57,   88, 2469,  184, 1966,  968,  605, 2827,
         137,  473,  531,  367,  471,  840,  409,   49,  962, 1086,  195,  635,
         664,  264, 1319,  797,  199, 12

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.2]

tensor([4351, 3944, 5552, 1091, 3196,  276, 1357,  100, 1314, 3039, 3973, 2858,
        2939,  969, 4356, 3571, 4386,  249, 1890, 5015, 2201, 5780, 4094, 2649,
        1414, 3963, 1735, 2088, 1530, 3055, 4386, 4394, 3530, 4808, 2900, 4153,
        1691, 4275, 3654, 5165,  739, 1126, 1923, 4858, 5226, 2897, 1676, 5558,
        3232, 5568, 4529, 2327, 4911, 3755, 2111, 4662,  489, 4283, 5157, 1885,
        1060, 1034, 3407, 1371, 3831,  421, 1379, 2963, 6011, 1675, 4838, 2797,
        1582, 3540, 4103, 1594, 2469,  425,  260, 1918, 2748, 2660, 5194, 2352,
        2097, 1117,  164, 1366,  429,   76, 4333, 1445, 4435, 1117,  696, 4907,
        5682, 1606, 3817, 4021, 5783,  466, 4221, 4153, 4270, 3171,  611,  183,
        2462,  306, 2106, 1311, 2669,  412, 5484, 2748, 1147, 4334, 3020, 5618,
         285, 1255,  181, 5217, 5108, 2035, 5497, 4104, 4280, 1121, 2623, 2911,
        4124, 5133, 5464, 2098,  928, 5083, 1890, 4280, 1869,  903, 3721, 5182,
        2858, 4906, 2840, 2790, 2318, 53

  0%|          | 0/50 [00:00<?, ?it/s, loss=1.19]

tensor([4., 3., 3., 5., 5., 5., 2., 1., 3., 4., 4., 3., 3., 3., 4., 5., 3., 4.,
        4., 4., 3., 4., 5., 3., 4., 5., 3., 3., 4., 3., 3., 3., 4., 4., 5., 4.,
        2., 4., 3., 3., 4., 4., 5., 4., 4., 3., 3., 4., 3., 5., 4., 4., 4., 5.,
        3., 5., 4., 3., 5., 5., 5., 3., 2., 3., 4., 4., 4., 4., 1., 4., 5., 4.,
        5., 4., 4., 4., 3., 3., 4., 4., 4., 3., 5., 2., 2., 3., 4., 3., 3., 3.,
        3., 3., 5., 3., 4., 3., 2., 4., 4., 4., 4., 5., 5., 3., 5., 2., 3., 4.,
        3., 4., 5., 3., 3., 3., 2., 4., 4., 4., 4., 4., 4., 5., 4., 4., 4., 3.,
        4., 5., 4., 1., 4., 3., 4., 4., 1., 4., 2., 1., 4., 4., 1., 3., 1., 3.,
        4., 5., 3., 3., 4., 3., 4., 3., 3., 1., 2., 2., 3., 3., 3., 2., 5., 4.,
        2., 4., 3., 2., 3., 4., 5., 4., 3., 2., 5., 3., 4., 5., 4., 3., 4., 3.,
        5., 5., 5., 5., 2., 4., 5., 5., 3., 5., 4., 2., 3., 2., 4., 4., 3., 4.,
        3., 4., 4., 3., 4., 3., 5., 4., 4., 4., 3., 5., 3., 3., 3., 4., 3., 2.,
        5., 5., 4., 2., 3., 3., 4., 4., 

  0%|          | 0/50 [00:01<?, ?it/s, loss=1.19]

tensor([4., 4., 4., 4., 2., 4., 4., 5., 5., 5., 3., 3., 5., 4., 4., 4., 5., 5.,
        4., 4., 4., 4., 5., 3., 4., 4., 4., 2., 1., 5., 5., 5., 5., 4., 4., 4.,
        4., 3., 3., 4., 3., 3., 4., 4., 4., 5., 3., 5., 4., 3., 4., 3., 4., 3.,
        3., 3., 2., 5., 5., 4., 5., 3., 5., 4., 1., 3., 5., 4., 3., 3., 2., 5.,
        5., 5., 5., 2., 3., 4., 4., 1., 3., 5., 3., 4., 1., 1., 5., 3., 4., 2.,
        3., 5., 5., 2., 3., 5., 5., 3., 4., 4., 5., 3., 3., 4., 4., 3., 4., 4.,
        3., 3., 3., 3., 2., 5., 2., 3., 5., 5., 2., 3., 2., 5., 5., 5., 2., 5.,
        3., 2., 4., 3., 2., 4., 3., 3., 4., 5., 4., 3., 4., 4., 5., 3., 3., 4.,
        1., 5., 4., 3., 2., 3., 2., 2., 1., 5., 3., 4., 5., 4., 4., 5., 2., 4.,
        5., 4., 3., 5., 5., 3., 3., 4., 4., 4., 4., 4., 3., 4., 4., 5., 4., 4.,
        1., 4., 2., 1., 4., 5., 2., 2., 2., 2., 4., 3., 2., 1., 4., 3., 4., 3.,
        4., 4., 3., 4., 4., 3., 5., 5., 5., 4., 4., 4., 4., 3., 3., 4., 5., 4.,
        3., 4., 5., 3., 5., 2., 3., 5., 

  0%|          | 0/50 [00:01<?, ?it/s, loss=1.19]

tensor([3., 3., 4., 3., 5., 3., 3., 2., 5., 3., 3., 3., 3., 3., 3., 5., 5., 3.,
        5., 3., 4., 5., 2., 4., 4., 5., 4., 3., 3., 4., 4., 4., 3., 3., 1., 2.,
        4., 3., 3., 2., 5., 4., 2., 2., 5., 4., 5., 5., 5., 4., 4., 3., 2., 3.,
        4., 4., 5., 4., 2., 4., 4., 1., 4., 5., 4., 2., 3., 2., 1., 4., 5., 5.,
        4., 4., 4., 5., 4., 4., 5., 5., 5., 2., 3., 3., 1., 1., 5., 4., 3., 3.,
        4., 2., 3., 1., 3., 5., 5., 1., 3., 4., 3., 4., 2., 4., 1., 3., 3., 2.,
        4., 3., 4., 1., 3., 2., 2., 2., 2., 5., 4., 3., 4., 5., 4., 3., 4., 4.,
        3., 4., 4., 4., 5., 5., 4., 2., 3., 3., 3., 3., 5., 4., 2., 5., 3., 4.,
        3., 3., 3., 1., 4., 5., 4., 1., 3., 4., 5., 2., 4., 3., 4., 5., 4., 5.,
        3., 5., 1., 5., 3., 4., 5., 5., 4., 5., 5., 4., 5., 3., 3., 4., 4., 5.,
        5., 5., 5., 4., 3., 4., 1., 3., 2., 5., 3., 4., 2., 4., 5., 5., 3., 4.,
        1., 2., 3., 4., 2., 4., 5., 2., 3., 4., 5., 4., 5., 3., 3., 5., 3., 2.,
        3., 4., 2., 3., 5., 4., 4., 5., 

  0%|          | 0/50 [00:01<?, ?it/s, loss=1.19]

./././././././.
tensor([5., 3., 4., 5., 3., 3., 4., 3., 3., 2., 2., 4., 4., 3., 3., 3., 4., 4.,
        2., 3., 5., 2., 2., 5., 4., 3., 5., 2., 5., 5., 4., 4., 1., 3., 3., 5.,
        5., 3., 5., 4., 3., 5., 3., 5., 2., 4., 3., 4., 4., 1., 2., 5., 5., 5.,
        4., 1., 4., 2., 2., 3., 4., 3., 4., 4., 5., 4., 4., 5., 4., 4., 3., 3.,
        4., 3., 4., 3., 1., 3., 4., 3., 5., 3., 3., 3., 3., 2., 5., 3., 2., 4.,
        2., 4., 5., 3., 5., 3., 2., 2., 4., 4., 4., 4., 4., 4., 1., 5., 5., 2.,
        4., 4., 4., 4., 4., 3., 3., 4., 2., 4., 4., 3., 3., 4., 5., 1., 3., 2.,
        3., 3., 4., 3., 4., 3., 3., 3., 4., 3., 4., 3., 3., 4., 4., 5., 4., 4.,
        3., 3., 4., 3., 2., 4., 2., 3., 4., 3., 1., 4., 4., 2., 5., 4., 4., 4.,
        4., 3., 5., 5., 3., 4., 2., 4., 5., 1., 5., 5., 4., 4., 1., 2., 4., 3.,
        4., 3., 2., 5., 2., 4., 4., 4., 2., 4., 2., 5., 3., 4., 5., 2., 4., 2.,
        2., 3., 4., 5., 2., 5., 4., 3., 3., 4., 5., 3., 2., 5., 4., 3., 3., 4.,
        2., 2., 5., 5., 

  0%|          | 0/50 [00:01<?, ?it/s, loss=1.19]

./././././././.
tensor([5., 3., 2., 4., 5., 2., 4., 2., 3., 2., 1., 3., 3., 5., 5., 4., 5., 4.,
        3., 3., 4., 1., 4., 2., 4., 4., 4., 5., 3., 4., 4., 4., 4., 5., 5., 4.,
        4., 5., 2., 4., 2., 5., 1., 3., 3., 3., 5., 3., 5., 2., 3., 3., 1., 4.,
        4., 3., 1., 4., 3., 4., 3., 5., 4., 5., 5., 4., 4., 4., 3., 5., 3., 4.,
        4., 3., 3., 5., 2., 4., 2., 3., 4., 5., 4., 4., 3., 4., 3., 4., 1., 5.,
        4., 3., 3., 5., 4., 3., 5., 1., 5., 4., 3., 4., 2., 2., 3., 4., 2., 4.,
        3., 5., 5., 4., 4., 3., 3., 4., 3., 5., 3., 2., 3., 3., 4., 3., 5., 4.,
        3., 4., 5., 4., 2., 2., 4., 1., 4., 4., 3., 4., 4., 4., 5., 4., 4., 5.,
        4., 4., 5., 3., 4., 3., 3., 5., 5., 2., 4., 4., 2., 3., 4., 5., 4., 4.,
        5., 3., 4., 4., 3., 3., 4., 3., 3., 5., 4., 4., 2., 5., 4., 3., 4., 4.,
        3., 5., 4., 5., 5., 3., 4., 4., 4., 4., 4., 5., 3., 1., 4., 1., 5., 3.,
        4., 4., 2., 4., 3., 4., 4., 4., 5., 5., 4., 2., 2., 1., 3., 4., 4., 5.,
        1., 4., 4., 3., 

  0%|          | 0/50 [00:01<?, ?it/s, loss=1.19]

./././././././.
tensor([5., 3., 5., 1., 3., 4., 4., 5., 4., 1., 3., 3., 3., 4., 5., 4., 4., 4.,
        4., 5., 3., 5., 4., 1., 1., 4., 2., 5., 4., 5., 3., 1., 5., 5., 3., 4.,
        4., 4., 5., 5., 5., 5., 4., 3., 4., 3., 5., 3., 3., 4., 5., 1., 1., 5.,
        5., 1., 5., 5., 4., 3., 5., 5., 3., 4., 1., 2., 5., 2., 4., 5., 5., 4.,
        4., 3., 5., 5., 5., 5., 4., 4., 4., 4., 3., 3., 5., 4., 5., 5., 4., 4.,
        5., 5., 5., 5., 4., 2., 3., 4., 2., 2., 5., 3., 5., 5., 4., 1., 5., 3.,
        4., 4., 3., 5., 4., 4., 4., 5., 4., 3., 4., 5., 2., 4., 4., 3., 3., 4.,
        5., 5., 4., 5., 1., 3., 4., 4., 2., 4., 4., 5., 4., 4., 5., 5., 3., 4.,
        4., 4., 4., 3., 2., 4., 3., 4., 4., 3., 4., 3., 4., 4., 2., 2., 4., 3.,
        2., 5., 3., 5., 2., 5., 2., 3., 5., 5., 4., 3., 5., 5., 3., 3., 4., 4.,
        4., 4., 3., 4., 3., 1., 3., 5., 3., 1., 5., 5., 5., 4., 2., 2., 5., 5.,
        3., 4., 5., 4., 4., 3., 2., 4., 4., 3., 3., 4., 5., 3., 5., 3., 4., 5.,
        2., 4., 4., 5., 

  0%|          | 0/50 [00:01<?, ?it/s, loss=1.19]


KeyboardInterrupt: 

In [ ]:
user_ids = users.to_numpy()[:, 0]
item_ids = movies.to_numpy()[:, 2]

In [ ]:
# get the top_k ratings for all users:
top_k=50
reco_matrix = np.zeros((len(user_ids), top_k), dtype=int)

for u in user_ids:
    reco_items, all_scores = model.rank(user_idx=u, item_indices=list(item_ids))
    reco_matrix[u] = reco_items[:top_k]

In [ ]:
####IR Metrics####
####Precision####
from cornac.mymetrics.GenrePrecision import GenrePrecision

gp = GenrePrecision(users, unique_genres)
MF_gp = gp.compute(reco_matrix, movies)

In [ ]:
rating_data

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

matrices = [MF_gp]


values1 = matrices[0]
labels = unique_genres
bar_width = 0.25
titles = ["MF_gp"]


fig, axs = plt.subplots(2, 3, figsize=(18, 12))
axs = axs.flatten()


for i in range(len(matrices)):
    axs[i].bar(labels, matrices[i], color="skyblue")
    axs[i].set_title(titles[i])
    axs[i].set_xlabel("Genres")
    axs[i].set_ylabel("Values")
    axs[i].tick_params(
        axis="x", rotation=90
    ) 

# Adjust layout
plt.tight_layout()
plt.show()

In [ ]:
item_features_numpy.shape

In [ ]:
dataset


In [ ]:
        |   RMSE |    AUC | Train (s) | Test (s)
------- + ------ + ------ + --------- + --------
lmd0.02 | 1.0251 | 0.6337 |  117.4954 |   3.6938

In [ ]:
print(type(user_features_numpy[:,1]))

In [ ]:
print(user_features_numpy[:,1].shape)